import { defineConfig } from '@playwright/test';
import dotenv from 'dotenv';
dotenv.config();

export default defineConfig({
  // testDir: './tests',

  // Run login once before all tests to create storageState
  // globalSetup: './utils/auth/global-login.setup.ts',

  // Increase timeout for debugging
  timeout: 4 * 60 * 1000,
  

  // Show detailed test output
  reporter: [
    ["allure-playwright"],
    ["junit", { outputFile: "test-results/junit.xml" }],
  ],

  use: {
    // baseURL: 'https://safaricom-partnerhub.safaricom.et',
    // baseURL:"https://one-platform-um-fe.oat.sma2.safaricomet.net",
     baseURL: 'https://www.saucedemo.com/',

    // Run headless in CI
    headless: !!process.env.CI,
  

    // Slow down each action (very useful)
    // launchOptions: {
    //   slowMo: 300, // adjust (100–500)
    // },

    // Capture screenshots at every step
    screenshot: 'on',

    // Record video for all tests
    video: 'on',

    // 🔥 Enable full tracing (screenshots, snapshots, source)
    trace: 'on',

    // See browser console logs
    actionTimeout: 30 * 1000,
    navigationTimeout: 60 * 1000,

    // Ignore HTTPS issues if any
    ignoreHTTPSErrors: true,

    // Better debugging context
    // viewport: { width: 1280, height: 720 },
      viewport: null,
      
  launchOptions: {
    args: ['--start-maximized'],
  },

//   launchOptions: {
//   args: ['--force-device-scale-factor=0.8']
// },

    // Reuse authenticated state generated by global setup
    storageState: 'storageState.json',
  },

});
